FROM php:5-fpm
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
        libmagickwand-dev \
        libmemcached-dev
RUN docker-php-ext-install -j$(nproc) mysql iconv mcrypt mysqli pdo_mysql
RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
RUN docker-php-ext-install -j$(nproc) gd
# RUN pecl install memcached && docker-php-ext-enable memcached
RUN pecl install xdebug && docker-php-ext-enable xdebug
RUN yes '' | pecl install -f imagick
RUN docker-php-ext-enable imagick 
RUN docker-php-ext-enable opcache
